tests/distribution/distribution3.fut:
Command failed with ExitFailure 1:
./tests/distribution/distribution3 --cache-file tests/distribution/distribution3.fut.cache
Stderr:
./tests/distribution/distribution3: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(4098): error: "gtid_6098" has already been declared in the current scope
      int64_t gtid_6098;
              ^

futhark-cuda(4099): error: "gtid_6099" has already been declared in the current scope
      int64_t gtid_6099;
              ^

futhark-cuda(4113): error: "gtid_6109" has already been declared in the current scope
      int64_t gtid_6109;
              ^

futhark-cuda(4114): error: "gtid_6110" has already been declared in the current scope
      int64_t gtid_6110;
              ^

4 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/distribution/distribution2.fut:
Command failed with ExitFailure 1:
./tests/distribution/distribution2 --cache-file tests/distribution/distribution2.fut.cache
Stderr:
./tests/distribution/distribution2: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(4636): error: "gtid_8610" has already been declared in the current scope
      int64_t gtid_8610;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/existential-ifs/partition.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/existential-ifs/partition --cache-file tests/existential-ifs/partition.fut.cache:
Entry point: main; dataset: #0 ("[1i32, 1i32, 1i32, 1i32, 1i32]"):
tests/existential-ifs/partition.fut.main.0.actual and tests/existential-ifs/partition.fut.main.0.expected do not match:
Value #0 index [1]: expected 1, got 0
...and 3 other mismatches.
tests/tokens.fut:
After sending command "call" to server process:fd:14: hGetLine: end of file
Server stderr:

CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:279:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.sendCommand (src/Futhark/Server.hs:(258,1)-(286,21))
  Futhark.Server.cmdCall (src/Futhark/Server.hs:(338,1)-(339,44))
  Futhark.CLI.Test.context1 (src/Futhark/CLI/Test.hs:67:1-48)
  Futhark.CLI.Test.runCompiledEntry (src/Futhark/CLI/Test.hs:(339,1)-(377,54))
  Control.Concurrent.Async.Internal.catchAll (Control/Concurrent/Async/Internal.hs:858:1-16)
  Control.Concurrent.Async.Internal.concurrently' (Control/Concurrent/Async/Internal.hs:(649,1)-(694,16))
  Control.Concurrent.Async.Internal.race (Control/Concurrent/Async/Internal.hs:(611,1)-(617,31))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/soacs/partition2.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/soacs/partition2 --cache-file tests/soacs/partition2.fut.cache:
Entry point: main; dataset: #0 ("[2i32, 7i32, 1i32, 2i32, 8i32, 9i32, 1i32, 5i32, 0..."):
tests/soacs/partition2.fut.main.0.actual and tests/soacs/partition2.fut.main.0.expected do not match:
Value #2 index [0]: expected 8, got 32639
...and 10 other mismatches.
tests/soacs/filter3.fut:
Compiling with --backend=cuda:
Warning at tests/soacs/filter3.fut:12:27-28:
  Unused name "i".
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'simplify':
In function entry_main
When checking function body
In expression of statement
  {tmp_6180 : ({}, i64)}
in body of case {true}
Type error:
Type annotation is
  {i64}
But result returns type
  {i32}


tests/soacs/partition1.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/soacs/partition1 --cache-file tests/soacs/partition1.fut.cache:
Entry point: main; dataset: #0 ("[0i32, 1i32, 2i32, 3i32, 4i32, 5i32, 6i32, 7i32, 8..."):
tests/soacs/partition1.fut.main.0.actual and tests/soacs/partition1.fut.main.0.expected do not match:
Value #1 index [0]: expected 3, got 32699
...and 4 other mismatches.
tests/issue1753.fut:
Compiling with --backend=cuda:

tests/rosettacode/filter.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/rosettacode/filter --cache-file tests/rosettacode/filter.fut.cache:
Entry point: main; dataset: #0 ("[1i32, 2i32, 3i32, 4i32, 5i32, 6i32, 7i32, 8i32, 9..."):
tests/rosettacode/filter.fut.main.0.actual and tests/rosettacode/filter.fut.main.0.expected do not match:
Value #0 index [0]: expected 2, got 0
...and 3 other mismatches.
tests/rosettacode/amicablepairs.fut:
Compiling with --backend=cuda:
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'simplify':
In function entry_main
When checking function body
In expression of statement
  {defunc_0_filter_res_7553 : ({}, i64),
   defunc_0_filter_res_7555 : ({}, i64),
   defunc_0_filter_res_7557 : ({defunc_0_filter_res_7559}, [defunc_0_filter_res_7553]i32),
   defunc_0_filter_res_7559 : ({defunc_0_filter_res_7557}, [defunc_0_filter_res_7555]i32)}
in body of last case
In expression of statement
  {scatter_res_7858 : ({}, [d<{(*) upper upper}>_7444]i32),
   scatter_res_7859 : ({}, [d<{(*) upper upper}>_7444]i32)}
Type error:
Anonymous function defined with 4 parameters:
[eta_p_7778 : i64, eta_p_7777 : i64, write_value_7779 : i32, write_value_7780 : i32]
but expected to take 2 arguments.

tests/issue1435.fut:
Command failed with ExitFailure 1:
./tests/issue1435 --cache-file tests/issue1435.fut.cache
Stderr:
./tests/issue1435: Error during context initialisation:
Index [-1] out of bounds for array of shape [3].
-> #0  tests/issue1435.fut:29:22-27

CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/quickmedian.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/quickmedian --cache-file tests/quickmedian.fut.cache:
Entry point: main; dataset: #1 ("[4i32, -8i32, 2i32, 2i32, 0i32, 0i32, 5i32, 9i32, ..."):
tests/quickmedian.fut.main.1.actual and tests/quickmedian.fut.main.1.expected do not match:
Value #0: expected 0, got 224
tests/psums.fut:
Command failed with ExitFailure 1:
./tests/psums --cache-file tests/psums.fut.cache
Stderr:
./tests/psums: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3909): error: "gtid_6191" has already been declared in the current scope
      int64_t gtid_6191;
              ^

futhark-cuda(3923): error: "gtid_6203" has already been declared in the current scope
      int64_t gtid_6203;
              ^

futhark-cuda(3937): error: "gtid_6215" has already been declared in the current scope
      int64_t gtid_6215;
              ^

3 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/fusion/fuseFilter1.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/fusion/fuseFilter1 --cache-file tests/fusion/fuseFilter1.fut.cache:
Entry point: main; dataset: #0 ("[3i32, 5i32, -2i32, 3i32, 4i32, -30i32] [-4i32, 10..."):
tests/fusion/fuseFilter1.fut.main.0.actual and tests/fusion/fuseFilter1.fut.main.0.expected do not match:
Value #0 index [1]: expected 4, got 0
tests/fusion/WithAccs/ker2-radix.fut:
Command failed with ExitFailure 1:
./tests/fusion/WithAccs/ker2-radix --cache-file tests/fusion/WithAccs/ker2-radix.fut.cache
Stderr:
./tests/fusion/WithAccs/ker2-radix: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(4163): error: "gtid_10816" has already been declared in the current scope
          int64_t gtid_10816;
                  ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/fusion/fuseFilter2.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/fusion/fuseFilter2 --cache-file tests/fusion/fuseFilter2.fut.cache:
Entry point: main; dataset: #0 ("[1i32, 2i32, 3i32, 4i32] [5i32, 6i32, 7i32, 8i32]"):
tests/fusion/fuseFilter2.fut.main.0.actual and tests/fusion/fuseFilter2.fut.main.0.expected do not match:
Value #0: expected 26, got 229
tests/fusion/filter-filter1.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/fusion/filter-filter1 --cache-file tests/fusion/filter-filter1.fut.cache:
Entry point: main; dataset: #0 ("[1i32, 2i32, 3i32, 4i32, 5i32, 6i32, 7i32, 8i32, 9..."):
tests/fusion/filter-filter1.fut.main.0.actual and tests/fusion/filter-filter1.fut.main.0.expected do not match:
Value #0 index [1]: expected 30, got -1
...and 4 other mismatches.
tests/fusion/fusion4.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/fusion/fusion4 --cache-file tests/fusion/fusion4.fut.cache:
Entry point: main; dataset: #0 ("[9i32, -3i32, 5i32, 2i32]"):
tests/fusion/fusion4.fut.main.0.actual and tests/fusion/fusion4.fut.main.0.expected do not match:
Value #0: expected 6, got 9
tests/fusion/fuse-across-transpose6.fut:
Command failed with ExitFailure 1:
./tests/fusion/fuse-across-transpose6 --cache-file tests/fusion/fuse-across-transpose6.fut.cache
Stderr:
./tests/fusion/fuse-across-transpose6: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(4120): error: "gtid_7553" has already been declared in the current scope
      int64_t gtid_7553;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/fusion/Vers2.0/maposcanomaposcan.fut:
Compiling with --backend=cuda:
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'simplify':
In function entry_main
When checking function body
When matching
   {defunc_0_map_res_5856 : ({}, [d₀_5684]f64)}
with
   segscan(thread; ; grid=num_tblocks_5883; blocksize=segscan_tblock_size_5881)
   (gtid_5885 < d₀_5684) (~phys_tid_5886)
   : {f64} {
     let {x_5770 : ({}, f64)} =
       res_5874[0i64, gtid_5885]
     return {returns x_5770}
   }
   ({0.0f64},
   ,
   \ {eta_p_5758 : f64,
      eta_p_5759 : f64}
     : {f64} ->
     let {defunc_0_op_res_5760 : ({}, f64)} =
       fadd64(eta_p_5758, eta_p_5759)
     in {defunc_0_op_res_5760})
   \ {eta_p_5762 : f64}
     : {f64,
        f64} ->
     let {lifted_lambda_res_5763 : ({}, f64)} =
       fadd64(5.0f64, eta_p_5762)
     in {lifted_lambda_res_5763, eta_p_5762},

Pat
{defunc_0_map_res_5856 : ({}, [d₀_5684]f64)}
cannot match value of type
{[d₀_5684]f64,
 [d₀_5684]f64}.

tests/fusion/Vers2.0/maposcan0.fut:
Compiling with --backend=cuda:
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'simplify':
In function entry_main
When checking function body
When matching
   {defunc_0_map_res_5573 : ({}, [d₀_5536]f64)}
with
   segscan(thread; ; grid=num_tblocks_5579; blocksize=segscan_tblock_size_5577)
   (gtid_5581 < d₀_5536) (~phys_tid_5582)
   : {f64} {
     let {x_5572 : ({}, f64)} =
       arr_5537[gtid_5581]
     return {returns x_5572}
   }
   ({0.0f64},
   ,
   \ {eta_p_5565 : f64,
      eta_p_5566 : f64}
     : {f64} ->
     let {defunc_0_op_res_5567 : ({}, f64)} =
       fadd64(eta_p_5565, eta_p_5566)
     in {defunc_0_op_res_5567})
   \ {eta_p_5569 : f64}
     : {f64,
        f64} ->
     let {lifted_lambda_res_5570 : ({}, f64)} =
       fmul64(2.0f64, eta_p_5569)
     in {lifted_lambda_res_5570, eta_p_5569},

Pat
{defunc_0_map_res_5573 : ({}, [d₀_5536]f64)}
cannot match value of type
{[d₀_5536]f64,
 [d₀_5536]f64}.

tests/fusion/map-scan3.fut:
Command failed with ExitFailure 1:
./tests/fusion/map-scan3 --cache-file tests/fusion/map-scan3.fut.cache
Stderr:
./tests/fusion/map-scan3: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3980): error: "gtid_6132" has already been declared in the current scope
      int64_t gtid_6132;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/fusion/iswim3.fut:
Command failed with ExitFailure 1:
./tests/fusion/iswim3 --cache-file tests/fusion/iswim3.fut.cache
Stderr:
./tests/fusion/iswim3: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(4155): error: "gtid_6554" has already been declared in the current scope
      int64_t gtid_6554;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/memory-block-merging/coalescing/issue-2010.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/memory-block-merging/coalescing/issue-2010 --cache-file tests/memory-block-merging/coalescing/issue-2010.fut.cache:
Entry point: main; dataset: #0 ("[1i32, 2i32, 3i32, 4i32, 5i32, 6i32, 7i32]"):
tests/memory-block-merging/coalescing/issue-2010.fut.main.0.actual and tests/memory-block-merging/coalescing/issue-2010.fut.main.0.expected do not match:
Value #1 index [2]: expected 6, got 96
...and 4 other mismatches.
tests/quickselect.fut:
Compiling with --backend=cuda:
Running compiled program:
Running ./tests/quickselect --cache-file tests/quickselect.fut.cache:
Entry point: main; dataset: #1 ("[4i32, -8i32, 2i32, 2i32, 0i32, 0i32, 5i32, 9i32, ..."):
tests/quickselect.fut.main.1.actual and tests/quickselect.fut.main.1.expected do not match:
Value #0: expected 4, got -603973376
tests/intragroup/expansion0.fut:
Command failed with ExitFailure 1:
./tests/intragroup/expansion0 --cache-file tests/intragroup/expansion0.fut.cache
Stderr:
./tests/intragroup/expansion0: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3953): error: "gtid_5917" has already been declared in the current scope
              int64_t gtid_5917;
                      ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/segscan1.fut:
Command failed with ExitFailure 1:
./tests/intragroup/segscan1 --cache-file tests/intragroup/segscan1.fut.cache
Stderr:
./tests/intragroup/segscan1: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3916): error: "gtid_6575" has already been declared in the current scope
      int64_t gtid_6575;
              ^

futhark-cuda(3917): error: "gtid_6576" has already been declared in the current scope
      int64_t gtid_6576;
              ^

2 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/scan0.fut:
Command failed with ExitFailure 1:
./tests/intragroup/scan0 --cache-file tests/intragroup/scan0.fut.cache
Stderr:
./tests/intragroup/scan0: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3902): error: "gtid_5621" has already been declared in the current scope
      int64_t gtid_5621;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/complex-screma.fut:
Command failed with ExitFailure 1:
./tests/intragroup/complex-screma --cache-file tests/intragroup/complex-screma.fut.cache
Stderr:
./tests/intragroup/complex-screma: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3911): error: "gtid_5880" has already been declared in the current scope
      int64_t gtid_5880;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/segscan0.fut:
Command failed with ExitFailure 1:
./tests/intragroup/segscan0 --cache-file tests/intragroup/segscan0.fut.cache
Stderr:
./tests/intragroup/segscan0: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3905): error: "gtid_5794" has already been declared in the current scope
      int64_t gtid_5794;
              ^

futhark-cuda(3906): error: "gtid_5795" has already been declared in the current scope
      int64_t gtid_5795;
              ^

2 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/scan3.fut:
Command failed with ExitFailure 1:
./tests/intragroup/scan3 --cache-file tests/intragroup/scan3.fut.cache
Stderr:
./tests/intragroup/scan3: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3910): error: "gtid_5886" has already been declared in the current scope
      int64_t gtid_5886;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/inplace0.fut:
Command failed with ExitFailure 1:
./tests/intragroup/inplace0 --cache-file tests/intragroup/inplace0.fut.cache
Stderr:
./tests/intragroup/inplace0: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3907): error: "gtid_5793" has already been declared in the current scope
      int64_t gtid_5793;
              ^

futhark-cuda(3923): error: "gtid_5804" has already been declared in the current scope
      int64_t gtid_5804;
              ^

2 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/scan1.fut:
Command failed with ExitFailure 1:
./tests/intragroup/scan1 --cache-file tests/intragroup/scan1.fut.cache
Stderr:
./tests/intragroup/scan1: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3913): error: "gtid_5799" has already been declared in the current scope
      int64_t gtid_5799;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/big0.fut:
Command failed with ExitFailure 1:
./tests/intragroup/big0 --cache-file tests/intragroup/big0.fut.cache
Stderr:
./tests/intragroup/big0: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3980): error: "gtid_6145" has already been declared in the current scope
      int64_t gtid_6145;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/toomuch.fut:
Command failed with ExitFailure 1:
./tests/intragroup/toomuch --cache-file tests/intragroup/toomuch.fut.cache
Stderr:
./tests/intragroup/toomuch: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(4088): error: "gtid_16930" has already been declared in the current scope
      int64_t gtid_16930;
              ^

futhark-cuda(4123): error: "gtid_16966" has already been declared in the current scope
      int64_t gtid_16966;
              ^

futhark-cuda(4158): error: "gtid_17008" has already been declared in the current scope
      int64_t gtid_17008;
              ^

futhark-cuda(4193): error: "gtid_17050" has already been declared in the current scope
      int64_t gtid_17050;
              ^

futhark-cuda(4228): error: "gtid_17092" has already been declared in the current scope
      int64_t gtid_17092;
              ^

futhark-cuda(4263): error: "gtid_17134" has already been declared in the current scope
      int64_t gtid_17134;
              ^

futhark-cuda(4298): error: "gtid_17176" has already been declared in the current scope
      int64_t gtid_17176;
              ^

futhark-cuda(4333): error: "gtid_17218" has already been declared in the current scope
      int64_t gtid_17218;
              ^

futhark-cuda(4368): error: "gtid_17260" has already been declared in the current scope
      int64_t gtid_17260;
              ^

9 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/scan2.fut:
Command failed with ExitFailure 1:
./tests/intragroup/scan2 --cache-file tests/intragroup/scan2.fut.cache
Stderr:
./tests/intragroup/scan2: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3903): error: "gtid_5815" has already been declared in the current scope
      int64_t gtid_5815;
              ^

1 error detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/intragroup/segscan2.fut:
Command failed with ExitFailure 1:
./tests/intragroup/segscan2 --cache-file tests/intragroup/segscan2.fut.cache
Stderr:
./tests/intragroup/segscan2: During CUDA initialisation:
NVRTC compilation failed.

futhark-cuda(3905): error: "gtid_6005" has already been declared in the current scope
      int64_t gtid_6005;
              ^

futhark-cuda(3906): error: "gtid_6006" has already been declared in the current scope
      int64_t gtid_6006;
              ^

2 errors detected in the compilation of "futhark-cuda".



CallStack (from HasCallStack):
  error, called at src/Futhark/Server.hs:172:7 in futhark-server-1.2.3.0-7250c2740dc4c0abcfeb7145d73e8ff6bb7391dc27d7fb42db00f3b3fed324ff:Futhark.Server
CallStack (from -prof):
  Futhark.Server.startServer (src/Futhark/Server.hs:(136,1)-(178,21))
  Futhark.Server.withServer (src/Futhark/Server.hs:(202,1)-(214,37))
  Futhark.CLI.Test.pureTestResults (src/Futhark/CLI/Test.hs:(84,1)-(89,49))
  Futhark.CLI.Test.withProgramServer (src/Futhark/CLI/Test.hs:(96,1)-(116,25))
  Futhark.CLI.Test.context (src/Futhark/CLI/Test.hs:(61,1)-(64,40))
  Futhark.CLI.Test.runTestCase (src/Futhark/CLI/Test.hs:(255,1)-(326,70))
  Futhark.CLI.Test.runTestM (src/Futhark/CLI/Test.hs:55:1-61)
  Futhark.CLI.Test.catching (src/Futhark/CLI/Test.hs:(453,1)-(456,40))
  Futhark.CLI.Test.doTest (src/Futhark/CLI/Test.hs:459:1-42)
  Futhark.CLI.Test.runTest (src/Futhark/CLI/Test.hs:(470,1)-(474,37))
  Futhark.CLI.Test.runTests (src/Futhark/CLI/Test.hs:(555,1)-(662,22))
  Futhark.Util.Options.mainWithOptions (src/Futhark/Util/Options.hs:(34,1)-(53,71))
  Futhark.CLI.Test.main (src/Futhark/CLI/Test.hs:(843,1)-(846,54))
  Futhark.CLI.Main.commands (src/Futhark/CLI/Main.hs:(53,1)-(92,5))
  Futhark.CLI.Main.reportingIOErrors (src/Futhark/CLI/Main.hs:(107,1)-(145,27))
  Futhark.CLI.Main.main (src/Futhark/CLI/Main.hs:(149,1)-(160,68))
tests/localfunction11.fut:
Compiling with --backend=cuda:
Internal compiler error.  Please report this:
  https://github.com/diku-dk/futhark/issues
Type error after pass 'simplify':
In function entry_main
When checking function body
In expression of statement
  {defunc_0_f_res_6199 : ({}, i64),
   defunc_0_f_res_6200 : ({}, [defunc_0_f_res_6199]i32)}
in body of last case
In expression of statement
  {scatter_res_6275 : ({}, [d₀_5972]i32),
   defunc_0_scan_res_6276 : ({}, [d₀_5972]i64)}
in body of last case
When matching
   {scatter_res_6455 : ({}, [d₀_5972]i32)}
with
   segscan(thread; ; grid=num_tblocks_6453; blocksize=segscan_tblock_size_6452)
   (gtid_6456 < d₀_5972) (~phys_tid_6457)
   : {i64} {
     let {x_6458 : ({}, i64)} =
       scatter_res_map_acc_6411[gtid_6456]
     return {returns x_6458}
   }
   ({0i64},
   ,
   \ {eta_p_6459 : i64,
      eta_p_6460 : i64}
     : {i64} ->
     let {defunc_0_op_res_6461 : ({}, i64)} =
       add64(eta_p_6459, eta_p_6460)
     in {defunc_0_op_res_6461})
   \ {x_6462 : i64}
     : {i64} ->
     {x_6462},

Pat
{scatter_res_6455 : ({}, [d₀_5972]i32)}
cannot match value of type
{[d₀_5972]i64}.